### PR TITLE
removed fortune due to racist/sexist language in fortune package against lots of community guidelines

### PR DESCRIPTION
**Pull request by h4sh5**
removed fortune due to racist/sexist language in fortune package against lots of community guidelines

### CODE REVIEW

**Comment by atomheartother** [comment]
Can I get an example of racist or sexist language from fortune?

**Comment by h4sh5** [comment]
My prefix on this server is !!

Woman was God's second mistake.
        -- Nietzsche


My prefix on this server is !!

Jesus may love you, but I think you're garbage wrapped in skin.
        -- Michael O'Donohugh

 My prefix on this server is !!

WHOA!!  Ken and Barbie are having TOO MUCH FUN!!  It must be the
NEGATIVE IONS!!

**Comment by liilac** [comment]
> Can I get an example of racist or sexist language from fortune?

@atomheartother Refer to https://github.com/atomheartother/QTweet/issues/89 which describes the issue and includes examples of problematic language.

**Comment by atomheartother** [comment]
I'd be more in favor of making a fork of fortune that removes the few offensive lines rather than removing them altogether, that seems overkill for a feature which has basically never caused any problems until today.

**Comment by atomheartother** [comment]
Either that or add an option which lets servers turn fortunes off, but remove them altogether is silly.

**Comment by liilac** [comment]
> I'd be more in favor of making a fork of fortune that removes the few offensive lines rather than removing them altogether, that seems overkill for a feature which has basically never caused any problems until today.

I proposed alternatives in #88.

It is unfair to say `which has basically never caused any problems until today` as it is more likely the issues have simply not been reported. The `fortune-teller` returns fortunes randomly and so in all likelihood, many other bot users have seen them.

~~There exists the `fortune-teller-safe` fork already, in [NPM](https://www.npmjs.com/package/fortune-teller-safe) ([GitHub](https://github.com/bushmango/fortune)), as a possible alternative. This package is not maintained but minimal changes have been maid to `fortune-teller` itself since the fork.~~

Edit: `fortune-teller-safe` did not make any changes to the package and includes all the same content

**Comment by Vbitz** [comment]
The `fortune-teller-safe` excludes the fortunes marked as offensive (in the version included on `npm`. The linked GitHub repo has different code).

2 of the 3 examples @h4sh5 mentioned are part of the "safe" set of fortunes.

**Comment by atomheartother** [comment]
> It is unfair to say which has basically never caused any problems until today as it is more likely the issues have simply not been reported.

QTweet has been in production in 7000+ servers for years and I have never had a single report about fortune - rather it's mostly all been positive feedback. So yes there may be unreported instances but still, my point stands - it'd be silly to remove the feature completely for all users who enjoy the features for very few who don't find it to their taste.

I'm leaning more and more towards just letting people disable it per-guild.

**Comment by h4sh5** [comment]
It would be great if you implement a command that can turn it off - like `!!no-forture` or something similar.

**Comment by atomheartother** [comment]
Either way it won't happen on this branch, closing it and moving the discussion to #89.

**Pull request closed without merging**
